### ISSUE TITLE
Flesh out Signature Info

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#130]
Now that #110 has landed we need to do the following:

* [x] Display comments for function signatures (#167)
* [ ] Display comments for function arguments
* [x] Render markdown for comments (#167)
* [ ] Fully support tuple structs
* [ ] Add module information (and impl/trait info?) to the returned documentation
* [ ] Provide a better list of candidate functions (`index_resolve` does not always pick the correct function) and pick the most appropriate one for what the user has currently typed
* [ ] Provide label offsets instead of the full label for parameter info (#296)
