### ISSUE TITLE
Tracking issue for inferring type of macro call to `vec!`

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#1842]
This is a tracking issue for correctly inferring type of macro call to `vec![]` `vec![1, 2]`, `vec![1, 2,]` or `vec![1; 2]`.

**Blocking issue/PRs**:
- [x] Macro resolving
  - [x] `#[macro_export]` and (auto) `#[macro_use]` for `std` ( #1743 )
  - [x] Macro scoping ( #1784 )
  - [x] `use` macros for `std` ( #1795 )
    ```
    pub use alloc_crate::vec;
    ```
- [x] Invoking with element-and-size
    ```
    ($elem:expr; $n:expr) => ( $crate::vec::from_elem($elem, $n) );
    ```
  - [x] `$crate` in macros ( #1815 )
- [x] Invoking with element-list
  ```
  ($($x:expr),*) => ( <[_]>::into_vec(box [$($x),*]) );
  ($($x:expr,)*) => ( $crate::vec![$($x),*] );
  ```
  - [x] `box` expression: ( #1818 )
  - [x] Type based path  `<[_]>::into_vec` ( #1817 )
  - [x] Type coercion `Box<[T; N]> -> Box<[T]>` ( #1823 )
  - [x] `liballoc::boxed::*` is not resolved. `cfg(test)` is not handled correctly ( #1920 )

**Related issue**: #1688 #1785

**Comment by marcogroppo** [comment]
It seems to be working now! 🎉

And on this codebase:

```
Expressions of unknown type: 7607 (8%)
Expressions of partially unknown type: 3591 (4%)
```

**Comment by lnicola** [comment]
Wait, is that right? With e1c367595139f109fb6f53811bed7d67a384793e I get

```
Database loaded, 214 roots, 290.198345ms
Crates in this dir: 27
Total modules found: 302
Total declarations: 10412
Total functions: 3666
Item Collection: 12.424421228s, 0b allocated 0b resident
Total expressions: 83310
Expressions of unknown type: 6003 (7%)
Expressions of partially unknown type: 3300 (3%)
Type mismatches: 4069
Inference: 26.40182095s, 0b allocated 0b resident
Total: 38.826249299s, 0b allocated 0b resident
```

**Comment by marcogroppo** [comment]
@lnicola mmm I'm on d3872964 🤔 I double checked with a fresh clone of the repo and I still have:

```
Database loaded, 215 roots, 1.5753391s
Crates in this dir: 28
Total declarations: 10520
Total functions: 3692
Item Collection: 8.2222013s, 0b allocated 0b resident
Total expressions: 85028
Expressions of unknown type: 7607 (8%)
Expressions of partially unknown type: 3591 (4%)
Type mismatches: 3821
Inference: 25.257739s, 0b allocated 0b resident
```

I'm running `ra_cli.exe analysis-stats .` and the current directory is the one that contains the checkout.

**Comment by lnicola** [comment]
:scream_cat:
 
Are you running the newly-built `ra_cli.exe`? I'm on Linux, maybe that's the reason.

**Comment by oxalica** [comment]
It works now! :tada:
