### ISSUE TITLE
Steering Issue #1

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7325]
This the steering issue -- it documents our roadmap for the next six weeks!

Steering meeting: [link](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Steering.20meeting/near/223130509)

The overall theme of the sprint is end-user experience. Specific subissues:

* [ ] Enable proc macros by default: https://github.com/rust-analyzer/rust-analyzer/issues/7328
* [ ] Investigate memory usage https://github.com/rust-analyzer/rust-analyzer/issues/7330
* [ ] Finish rowan work: https://github.com/rust-analyzer/rust-analyzer/issues/6857
* [x] Provided we have sufficient bandwidth, look into resolving local items: ~~https://github.com/rust-analyzer/rust-analyzer/issues/5922~~ Mostly resolved by https://github.com/rust-analyzer/rust-analyzer/pull/7614 / https://github.com/rust-analyzer/rust-analyzer/pull/7627

**Comment by matklad** [comment]
We didn't ticked the boxes, but we made a great progress. 

Understandably, actually ticking the boxes turns out to be challenging. To get better at these, we decided to officially install @matklad as "cheif makes-sure-that-the-boxes-are-ticked officer" for the next cycle.
