### ISSUE TITLE
Steering issue #2

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7838]
This the steering issue -- it documents our roadmap for the next six weeks!

Steering meeting: [link](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Steering.20meeting/near/228244615)

The overall theme of the sprint is following through. Specific subissues:

* [x] Finish enabling proc macros by default: https://github.com/rust-analyzer/rust-analyzer/issues/7328
* [x] Finish rowan work: https://github.com/rust-analyzer/rust-analyzer/issues/6857
* [x] Optimize memory usage further:  #7330
* [x] Switch to chalk's representation of `Ty`s: https://github.com/rust-analyzer/rust-analyzer/issues/8313

Bonus:

* [x] Fix major bugs in local items resolution
* [ ] Parallelize Salsa

**Comment by matklad** [comment]
Status update: proc macros are on by default, rowan is being  merged into master this very moment.

**Comment by matklad** [comment]
Ok, that was a great sprint, we did everything we wanted to! (except || salsa, but that was bonus goal to begin with)

:1st_place_medal:
