### ISSUE TITLE
Tracking issue: Move to Chalk IR

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#8313]
We want to get rid of our own representations of types and related data in hir_ty (like `Ty`, `TraitRef` and so on), and instead use the versions from `chalk_ir` everywhere. This is a rather large refactoring, and to achieve it without doing a gigantic PR that takes months, we're gradually aligning our own representations to look like the Chalk versions, with the goal that in the end we can mostly just define `type Ty = chalk_ir::Ty<Interner>` and be done.

We're actually getting close to this goal; I [tried it to see where we are currently](https://github.com/rust-analyzer/rust-analyzer/compare/master...flodiebold:chalk-ir-move?expand=1) and we're at about 400 errors when doing the switch. Going through those errors, I found the following remaining tasks:

- [x] remove interner parameter from `Substitution::interned` (I added it wrongly)
- [x] move `Ty` inherent methods to free-standing, extension trait or builder (except those that exist on Chalk's `Ty` as well)
  - all the `is_xxx` and `as_xxx` and similar accessors should move to extension trait
  - `equals_ctor` and `builtin_deref` can be free-standing in the modules where they're used
  - `substs` and `substs_mut` would ideally be removed
- [x] same for `Substitution` (just `prefix` and `suffix` remaining)
- [x] rename `TyKind::Unknown` -> `Error`
- [x] rename `TyKind::ForeignType` -> `Foreign`
- [x] adjust `Lifetime` to be more like Chalk (i.e. there's an `interned` method that contains the actual enum)
- [x] `self_type_parameter` takes Interner (on `TraitRef` and `ProjectionTy`)
- [x] remove all `Binders` `value` accesses, use `VariableKinds` instead of just a usize
  - make helper function for construction of `VariableKinds` with a number of type vars, since that's all we ever do right now
- [x] align `Binders::subst` with Chalk's `substitute`
- [x] hide `Substitution` internals, which are still getting accessed in lots of places
- [x] add lifetimes/consts to `TyKind::Ref`, `TyKind::Array`, `DynTy`
- [x] `FnPointer`: remove `num_args`, add `num_binders` (those are not the same), add `FnSubst`, `substs` -> `substitution`
- [x] remove `SolutionVariables`
- [x] move `InferenceVar` to `types` module and align it with the Chalk version (`to_inner` / `from_inner` should probably become free-standing functions in `unify.rs`

Note that lots of these can be easily done with [structural search & replace](https://rust-analyzer.github.io/manual.html#structural-search-and-replace)!

**Comment by flodiebold** [comment]
I will start moving out the `Ty` creation methods to a dedicated builder next.

**Comment by flodiebold** [comment]
I'll go for `Binders` next.

**Comment by Veykril** [comment]
I'll tackle `add lifetimes/consts to TyKind::Ref, TyKind::Array, DynTy`

**Comment by flodiebold** [comment]
@Veykril Great, keep in mind that for now we'll just always want to make them `'static` :slightly_smiling_face:

**Comment by flodiebold** [comment]
I'll do `FnPointer`.

**Comment by Veykril** [comment]
I'll move the accessors to the extension trait

**Comment by flodiebold** [comment]
I'm doing the remaining `substs`, `substs_mut` and `equals_ctor`.
