### ISSUE TITLE
Tracking issue: Completions showing up in places where they shouldn't

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#8518]
- [x] `pp` / `ppd` snippets are suggested in struct literals, where only the field names should appear
 - [x] inside trait definitions / impls (`trait Trait {$0}` / `impl Foo {$0}`), nothing except the `fn`, `type` and `const` keywords (and the full item completions for trait impls) should appear (currently many types and autoimport suggestions), (fixed in #8526 #9020)
 - [x] after `use`, many type names, macros etc. show up, which they shouldn't (ok, technically you can `use Vec;` if you want, but that's not really a useful suggestion?), (fixed in #9032)
 - [x] in type position (e.g. `let _: $0`), values like local variables, functions and constants show up, which they shouldn't. (fixed in #9181)
 - [ ] ideally we would only suggest macros in places where they can expand to something that works, but that's probably hard to impossible :thinking: if we can't detect it, maybe we could introduce annotations that can be added to macros to specify it.
 - [x] we should also hide `#[doc(hidden)]` or `#[unstable]` macros or items, e.g. `__thread_local_inner!`(cc #7718, #824, #2003)
 - [x] in expression or type position, we suggest attributes like `bench`, `derive`, `test`, `test_case`, `global_allocator`, `cfg_accessible` and `cfg_eval`. At least I think they're attributes? I'm actually not sure where they're coming from. (fixed in #9193)
 - [x] in expression/type position, we suggest derive macros like `Eq!(...)` or `Clone!(...)` as if one could actually call them that way. (fixed in https://github.com/rust-analyzer/rust-analyzer/pull/9182)

**Comment by SomeoneToIgnore** [comment]
For better clarity, it's preferable to add the corresponding tests into the `completions.rs` instead of a particular completion module.
This way, we will test all completions at once and ensure that there are no extra completions for all kinds of our completions, including the future added ones.

**Comment by Veykril** [comment]
> inside modules (and on top level), e.g. mod foo {$0}, nothing except various keywords that can introduce items should appear

Regarding this, are you referring to macros that shouldn't appear? As the only completions I get here are in fact item and vis keywords as well as macros which seems correct to me.

**Comment by flodiebold** [comment]
Yeah, I'm not sure what I meant, macros can appear there and so modules also need to.

**Comment by Veykril** [comment]
>  in expression or type position, we suggest attributes like bench, derive, test, test_case, global_allocator, cfg_accessible and cfg_eval. At least I think they're attributes? I'm actually not sure where they're coming from.

This seems to happen for all builtin 2.0 macros here 🤔
https://github.com/rust-lang/rust/blob/f6a28aa4036415d8aa713bf707842779b709935e/library/core/src/macros/mod.rs#L1396-L1490

**Comment by flodiebold** [comment]
Huh, ok, then it kind of makes sense that they show up. I guess the only way around it is to know in a hard-coded way (since these are built-in) that they're attribute macros? (What does rustc do? Writing e.g. `derive!(Foo)` just gives a normal "cannot find macro `derive` in this scope", nothing that indicates that it actually exists as a macro...)

**Comment by jonas-schievink** [comment]
Those are built-in attribute macros. We should add support for that to `hir_expand` (it should know all built-in macros, and also what kind of macros they are).

**Comment by Veykril** [comment]
I believe we can consider this tracking issue done? There is one open point left which is 

> ideally we would only suggest macros in places where they can expand to something that works, but that's probably hard to impossible 🤔 if we can't detect it, maybe we could introduce annotations that can be added to macros to specify it.

and for that I believe a standalone issue is more appropriate as its more about brainstorming what to do with that?

**Comment by jonas-schievink** [comment]
Yeah, closing this!
