### ISSUE TITLE
Steering issue #6

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9925]
[Zulip meeting link](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Steering.20meeting/near/249604899). This time, we'll finish up some issues from the last sprint, and also work on attribute macros to hopefully turn them on by default soon.

- [ ] https://github.com/rust-analyzer/rust-analyzer/issues/8961 get to 0 type mismatches on the RA repo
  - [ ] initial support for type mismatches diagnostic
- [ ] #9403 make our span tracking infra to work with `include!`
- [ ] https://github.com/rust-analyzer/rust-analyzer/issues/9868 push attribute macros over the finish line

Previous issue: https://github.com/rust-analyzer/rust-analyzer/issues/9580

**Comment by jonas-schievink** [comment]
Next steering issue: https://github.com/rust-analyzer/rust-analyzer/issues/10370
